package com.sap.cloud.sdk.tutorial;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;


@Entity
@Table(name = "profile_parameters")
public class ProfileParameters implements Serializable {
    private static final long serialVersionUID = 1L;

    // ID is automatically generated by the database
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name = "id", unique = true)
    private int id;

    @Column(name = "parameter_name")
    private String parameter_name;

    @Column(name = "default_value")
    private String default_value;

    @Column(name = "user_value")
    private String  user_value;

    @Column(name = "description")
    private String description;

    @Column(name = "company_subdomain")
    private String company_subdomain;

    public int getId() {
        return id;
    }

    public String getParameterName() {
        return parameter_name;
    }

    public String getDefaultValue() {
        return default_value;
    }

    public String getUserValue() {
        return user_value;
    }

    public String getDescription() {
        return description;
    }

    public String getCompanySubdomain() {
        return company_subdomain;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setParameterName(String parameter_name) {
        this.parameter_name = parameter_name;
    }

    public void setDefaultValue(String default_value) {
        this.default_value = default_value;
    }

    public void setUserValue(String user_value) {
        this.user_value = user_value;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setCompanySubdomain(String company_subdomain) {
        this.company_subdomain = company_subdomain;
    }
}

